# Ubuntu 14.04 Trusty support
dist: trusty
sudo: required

# Enable C++ support
language: cpp

# The branch to build
branches:
  only:
    - master

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    ####################################################################
    # Build with the main configuration on all the supported compilers #
    ####################################################################

    # Clang 3.7
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
      env: CC_VERSION=clang-3.7 CXX_VERSION=clang++-3.7
      before_install:
        - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.7 main'
        - sudo apt-get update -qq
        - sudo apt-get install -qq -y clang-3.7 lldb-3.7 libc++-dev libc++abi-dev

    # GCC 5
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - g++-5
            - gcc-5
      env: CC_VERSION=gcc-5 CXX_VERSION=g++-5

    # GCC 6
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - g++-6
            - gcc-6
      env: CC_VERSION=gcc-6 CXX_VERSION=g++-6

install:
  ###################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/ #
  ###################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  ##########################
  # Install a recent CMake #
  ##########################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - cmake --version

  ############################
  # Set the compiler version #
  ############################
  - if [[ "${CC_VERSION}" != "" ]]; then export CC=${CC_VERSION}; fi
  - if [[ "${CXX_VERSION}" != "" ]]; then export CXX=${CXX_VERSION}; fi

before_script:
  ####################################################################
  # Go back to the root of the project and setup the build directory #
  ####################################################################
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake ../

# Build steps
script:
  - make all

# Notifications settings
notifications:
  email:
    on_success: never
    on_failure: always
